package hibernate;
// Generated 2019-12-10 21:47:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Adresy generated by hbm2java
 */
public class Adresy  implements java.io.Serializable {


     private Integer adresId;
     private Klient klient;
     private String kraj;
     private String miasto;
     private String ulica;
     private String numerBudynku;
     private String numerLokalu;
     private String email;
     private Set hurtownias = new HashSet(0);

    public Adresy() {
    }

	
    public Adresy(Klient klient, String kraj, String miasto, String ulica, 
            String numerBudynku, String numerLokalu, String email) {
        this.klient = klient;
        this.kraj = kraj;
        this.miasto = miasto;
        this.ulica = ulica;
        this.numerBudynku = numerBudynku;
        this.numerLokalu = numerLokalu;
        this.email = email;
    }
    public Adresy(Klient klient, String kraj, String miasto, String ulica, 
            String numerBudynku, String numerLokalu, String email, 
            Set hurtownias) {
       this.klient = klient;
       this.kraj = kraj;
       this.miasto = miasto;
       this.ulica = ulica;
       this.numerBudynku = numerBudynku;
       this.numerLokalu = numerLokalu;
       this.email = email;
       this.hurtownias = hurtownias;
    }
   
    public Integer getAdresId() {
        return this.adresId;
    }
    
    public void setAdresId(Integer adresId) {
        this.adresId = adresId;
    }
    public Klient getKlient() {
        return this.klient;
    }
    
    public void setKlient(Klient klient) {
        this.klient = klient;
    }
    public String getKraj() {
        return this.kraj;
    }
    
    public void setKraj(String kraj) {
        this.kraj = kraj;
    }
    public String getMiasto() {
        return this.miasto;
    }
    
    public void setMiasto(String miasto) {
        this.miasto = miasto;
    }
    public String getUlica() {
        return this.ulica;
    }
    
    public void setUlica(String ulica) {
        this.ulica = ulica;
    }
    public String getNumerBudynku() {
        return this.numerBudynku;
    }
    
    public void setNumerBudynku(String numerBudynku) {
        this.numerBudynku = numerBudynku;
    }
    public String getNumerLokalu() {
        return this.numerLokalu;
    }
    
    public void setNumerLokalu(String numerLokalu) {
        this.numerLokalu = numerLokalu;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getHurtownias() {
        return this.hurtownias;
    }
    
    public void setHurtownias(Set hurtownias) {
        this.hurtownias = hurtownias;
    }




}


