package hibernate;
// Generated 2019-11-22 23:46:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Adresy generated by hbm2java
 */
public class Adresy  implements java.io.Serializable {


     private Integer adresId;
     private String kraj;
     private String miasto;
     private String ulica;
     private String numerBudynku;
     private int numerLokalu;
     private String email;
     private Set klients = new HashSet(0);
     private Set hurtownias = new HashSet(0);

    public Adresy() {
    }

	
    public Adresy(String kraj, String miasto, String ulica, String numerBudynku, int numerLokalu, String email) {
        this.kraj = kraj;
        this.miasto = miasto;
        this.ulica = ulica;
        this.numerBudynku = numerBudynku;
        this.numerLokalu = numerLokalu;
        this.email = email;
    }
    public Adresy(String kraj, String miasto, String ulica, String numerBudynku, int numerLokalu, String email, Set klients, Set hurtownias) {
       this.kraj = kraj;
       this.miasto = miasto;
       this.ulica = ulica;
       this.numerBudynku = numerBudynku;
       this.numerLokalu = numerLokalu;
       this.email = email;
       this.klients = klients;
       this.hurtownias = hurtownias;
    }
   
    public Integer getAdresId() {
        return this.adresId;
    }
    
    public void setAdresId(Integer adresId) {
        this.adresId = adresId;
    }
    public String getKraj() {
        return this.kraj;
    }
    
    public void setKraj(String kraj) {
        this.kraj = kraj;
    }
    public String getMiasto() {
        return this.miasto;
    }
    
    public void setMiasto(String miasto) {
        this.miasto = miasto;
    }
    public String getUlica() {
        return this.ulica;
    }
    
    public void setUlica(String ulica) {
        this.ulica = ulica;
    }
    public String getNumerBudynku() {
        return this.numerBudynku;
    }
    
    public void setNumerBudynku(String numerBudynku) {
        this.numerBudynku = numerBudynku;
    }
    public int getNumerLokalu() {
        return this.numerLokalu;
    }
    
    public void setNumerLokalu(int numerLokalu) {
        this.numerLokalu = numerLokalu;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getKlients() {
        return this.klients;
    }
    
    public void setKlients(Set klients) {
        this.klients = klients;
    }
    public Set getHurtownias() {
        return this.hurtownias;
    }
    
    public void setHurtownias(Set hurtownias) {
        this.hurtownias = hurtownias;
    }




}


