package hibernate;
// Generated 2019-12-03 21:04:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Kategorie generated by hbm2java
 */
public class Kategorie  implements java.io.Serializable {


     private Integer kategoriaId;
     private String nazwa;
     private String opis;
     private Set produkties = new HashSet(0);

    public Kategorie() {
    }

	
    public Kategorie(String nazwa, String opis) {
        this.nazwa = nazwa;
        this.opis = opis;
    }
    public Kategorie(String nazwa, String opis, Set produkties) {
       this.nazwa = nazwa;
       this.opis = opis;
       this.produkties = produkties;
    }
   
    public Integer getKategoriaId() {
        return this.kategoriaId;
    }
    
    public void setKategoriaId(Integer kategoriaId) {
        this.kategoriaId = kategoriaId;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public Set getProdukties() {
        return this.produkties;
    }
    
    public void setProdukties(Set produkties) {
        this.produkties = produkties;
    }




}


