package hibernate;
// Generated 2019-12-10 21:47:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.apache.commons.codec.digest.DigestUtils;

/**
 * Klient generated by hbm2java
 */
public class Klient  implements java.io.Serializable {


     private Integer klientId;
     private String imie;
     private String nazwisko;
     private long telefon;
     private String login;
     private String password;
     private Set adresies = new HashSet(0);

    public Klient() {
    }

	
    public Klient(String imie, String nazwisko, long telefon, String login, 
            String password) {
        this.imie = imie;
        this.nazwisko = nazwisko;
        this.telefon = telefon;
        this.login = login;
        this.password = password;
    }
    public Klient(String imie, String nazwisko, long telefon, String login,
            String password, Set adresies) {
       this.imie = imie;
       this.nazwisko = nazwisko;
       this.telefon = telefon;
       this.login = login;
       this.password = password;
       this.adresies = adresies;
    }
   
    public Integer getKlientId() {
        return this.klientId;
    }
    
    public void setKlientId(Integer klientId) {
        this.klientId = klientId;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public long getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(long telefon) {
        this.telefon = telefon;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
                //DigestUtils.shaHex(password); //hashowanie hasła w bazie
    }
    public Set getAdresies() {
        return this.adresies;
    }
    
    public void setAdresies(Set adresies) {
        this.adresies = adresies;
    }




}


