package hibernate;
// Generated 2019-12-03 21:04:59 by Hibernate Tools 4.3.1



/**
 * Klient generated by hbm2java
 */
public class Klient  implements java.io.Serializable {


     private Integer klientId;
     private Adresy adresy;
     private String imie;
     private String nazwisko;
     private long telefon;
     private String login;
     private String password;

    public Klient() {
    }

    public Klient(Adresy adresy, String imie, String nazwisko, long telefon, String login, String password) {
       this.adresy = adresy;
       this.imie = imie;
       this.nazwisko = nazwisko;
       this.telefon = telefon;
       this.login = login;
       this.password = password;
    }
   
    public Integer getKlientId() {
        return this.klientId;
    }
    
    public void setKlientId(Integer klientId) {
        this.klientId = klientId;
    }
    public Adresy getAdresy() {
        return this.adresy;
    }
    
    public void setAdresy(Adresy adresy) {
        this.adresy = adresy;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public long getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(long telefon) {
        this.telefon = telefon;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


