package hibernate;
// Generated 2019-11-22 23:46:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pracownik generated by hbm2java
 */
public class Pracownik  implements java.io.Serializable {


     private Integer pracownikId;
     private Uzytkownicy uzytkownicy;
     private String imie;
     private String nazwisko;
     private float placa;
     private String stanowisko;
     private Set wyplaties = new HashSet(0);

    public Pracownik() {
    }

	
    public Pracownik(Uzytkownicy uzytkownicy, String imie, String nazwisko, float placa, String stanowisko) {
        this.uzytkownicy = uzytkownicy;
        this.imie = imie;
        this.nazwisko = nazwisko;
        this.placa = placa;
        this.stanowisko = stanowisko;
    }
    public Pracownik(Uzytkownicy uzytkownicy, String imie, String nazwisko, float placa, String stanowisko, Set wyplaties) {
       this.uzytkownicy = uzytkownicy;
       this.imie = imie;
       this.nazwisko = nazwisko;
       this.placa = placa;
       this.stanowisko = stanowisko;
       this.wyplaties = wyplaties;
    }
   
    public Integer getPracownikId() {
        return this.pracownikId;
    }
    
    public void setPracownikId(Integer pracownikId) {
        this.pracownikId = pracownikId;
    }
    public Uzytkownicy getUzytkownicy() {
        return this.uzytkownicy;
    }
    
    public void setUzytkownicy(Uzytkownicy uzytkownicy) {
        this.uzytkownicy = uzytkownicy;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public float getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(float placa) {
        this.placa = placa;
    }
    public String getStanowisko() {
        return this.stanowisko;
    }
    
    public void setStanowisko(String stanowisko) {
        this.stanowisko = stanowisko;
    }
    public Set getWyplaties() {
        return this.wyplaties;
    }
    
    public void setWyplaties(Set wyplaties) {
        this.wyplaties = wyplaties;
    }




}


