package hibernate;
// Generated 2020-01-15 16:13:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Produkty generated by hbm2java
 */
public class Produkty  implements java.io.Serializable {


     private Integer produktId;
     private Kategorie kategorie;
     private String nazwa;
     private float cenaKupna;
     private String opis;
     private Set reklamas = new HashSet(0);
     private Set magazyns = new HashSet(0);
     private Set towaryzamowienies = new HashSet(0);

    public Produkty() {
    }

	
    public Produkty(Kategorie kategorie, String nazwa, float cenaKupna, String opis) {
        this.kategorie = kategorie;
        this.nazwa = nazwa;
        this.cenaKupna = cenaKupna;
        this.opis = opis;
    }
    public Produkty(Kategorie kategorie, String nazwa, float cenaKupna, String opis, Set reklamas, Set magazyns, Set towaryzamowienies) {
       this.kategorie = kategorie;
       this.nazwa = nazwa;
       this.cenaKupna = cenaKupna;
       this.opis = opis;
       this.reklamas = reklamas;
       this.magazyns = magazyns;
       this.towaryzamowienies = towaryzamowienies;
    }
   
    public Integer getProduktId() {
        return this.produktId;
    }
    
    public void setProduktId(Integer produktId) {
        this.produktId = produktId;
    }
    public Kategorie getKategorie() {
        return this.kategorie;
    }
    
    public void setKategorie(Kategorie kategorie) {
        this.kategorie = kategorie;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public float getCenaKupna() {
        return this.cenaKupna;
    }
    
    public void setCenaKupna(float cenaKupna) {
        this.cenaKupna = cenaKupna;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public Set getReklamas() {
        return this.reklamas;
    }
    
    public void setReklamas(Set reklamas) {
        this.reklamas = reklamas;
    }
    public Set getMagazyns() {
        return this.magazyns;
    }
    
    public void setMagazyns(Set magazyns) {
        this.magazyns = magazyns;
    }
    public Set getTowaryzamowienies() {
        return this.towaryzamowienies;
    }
    
    public void setTowaryzamowienies(Set towaryzamowienies) {
        this.towaryzamowienies = towaryzamowienies;
    }




}


