package hibernate;
// Generated 2019-12-10 21:47:49 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reklama generated by hbm2java
 */
public class Reklama  implements java.io.Serializable {


     private Integer reklamaId;
     private String tytul;
     private Date data;
     private String opis;
     private String grafika;
     private Integer ProduktID;

    public Reklama() {
    }

    public Reklama(String tytul, Date data, String opis, String grafika, int ProduktId) {
       this.tytul = tytul;
       this.data = data;
       this.opis = opis;
       this.grafika = grafika;
       this.ProduktID = ProduktId;
    }
   
    public Integer getReklamaId() {
        return this.reklamaId;
    }
    
    public void setReklamaId(Integer reklamaId) {
        this.reklamaId = reklamaId;
    }
    public String getTytul() {
        return this.tytul;
    }
    
    public void setTytul(String tytul) {
        this.tytul = tytul;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }

    public Integer getProduktID() {
        return ProduktID;
    }

    public void setProduktID(Integer ProduktID) {
        this.ProduktID = ProduktID;
    }
    public String getGrafika() {
        return this.grafika;
    }
    
    public void setGrafika(String grafika) {
        this.grafika = grafika;
    }




}


