package hibernate;
// Generated 2019-11-22 23:46:43 by Hibernate Tools 4.3.1



/**
 * Towaryzamowienie generated by hbm2java
 */
public class Towaryzamowienie  implements java.io.Serializable {


     private Integer towaryZamowienieId;
     private Produkty produkty;
     private Zamowienie zamowienie;
     private int ilosc;

    public Towaryzamowienie() {
    }

    public Towaryzamowienie(Produkty produkty, Zamowienie zamowienie, int ilosc) {
       this.produkty = produkty;
       this.zamowienie = zamowienie;
       this.ilosc = ilosc;
    }
   
    public Integer getTowaryZamowienieId() {
        return this.towaryZamowienieId;
    }
    
    public void setTowaryZamowienieId(Integer towaryZamowienieId) {
        this.towaryZamowienieId = towaryZamowienieId;
    }
    public Produkty getProdukty() {
        return this.produkty;
    }
    
    public void setProdukty(Produkty produkty) {
        this.produkty = produkty;
    }
    public Zamowienie getZamowienie() {
        return this.zamowienie;
    }
    
    public void setZamowienie(Zamowienie zamowienie) {
        this.zamowienie = zamowienie;
    }
    public int getIlosc() {
        return this.ilosc;
    }
    
    public void setIlosc(int ilosc) {
        this.ilosc = ilosc;
    }




}


