package hibernate;
// Generated 2020-01-15 16:13:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.List;
import org.hibernate.Criteria;
import org.hibernate.Session;

/**
 * Wyplaty generated by hbm2java
 */
public class Wyplaty  implements java.io.Serializable {


     private Integer wyplataId;
     public Pracownik pracownik;
     private Date data;
     private float kwota;

    public Wyplaty() {
    }

    public Wyplaty(Pracownik pracownik, Date data, float kwota) {
       this.pracownik = pracownik;
       this.data = data;
       this.kwota = kwota;
    }
   
    public Integer getWyplataId() {
        return this.wyplataId;
    }
    
    
    
    public void setWyplataId(Integer wyplataId) {
        this.wyplataId = wyplataId;
    }
    public Pracownik getPracownik() {
        return this.pracownik;
    }
    
    
    
    
    
    public void setPracownik(Pracownik pracownik) {
        this.pracownik = pracownik;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public float getKwota() {
        return this.kwota;
    }
    
    public void setKwota(float kwota) {
        this.kwota = kwota;
    }




}


