package hibernate;
// Generated 2020-01-15 16:13:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Zamowienie generated by hbm2java
 */
public class Zamowienie  implements java.io.Serializable {


     private Integer zamowienieId;
     private Klient klient;
     private String statusZaplaty;
     private String statusTransportu;
     private Date data;
     private Set towaryzamowienies = new HashSet(0);

    public Zamowienie() {
    }

	
    public Zamowienie(Klient klient, String statusZaplaty, String statusTransportu, Date data) {
        this.klient = klient;
        this.statusZaplaty = statusZaplaty;
        this.statusTransportu = statusTransportu;
        this.data = data;
    }
    public Zamowienie(Klient klient, String statusZaplaty, String statusTransportu, Date data, Set towaryzamowienies) {
       this.klient = klient;
       this.statusZaplaty = statusZaplaty;
       this.statusTransportu = statusTransportu;
       this.data = data;
       this.towaryzamowienies = towaryzamowienies;
    }
   
    public Integer getZamowienieId() {
        return this.zamowienieId;
    }
    
    public void setZamowienieId(Integer zamowienieId) {
        this.zamowienieId = zamowienieId;
    }
    public Klient getKlient() {
        return this.klient;
    }
    
    public void setKlient(Klient klient) {
        this.klient = klient;
    }
    public String getStatusZaplaty() {
        return this.statusZaplaty;
    }
    
    public void setStatusZaplaty(String statusZaplaty) {
        this.statusZaplaty = statusZaplaty;
    }
    public String getStatusTransportu() {
        return this.statusTransportu;
    }
    
    public void setStatusTransportu(String statusTransportu) {
        this.statusTransportu = statusTransportu;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Set getTowaryzamowienies() {
        return this.towaryzamowienies;
    }
    
    public void setTowaryzamowienies(Set towaryzamowienies) {
        this.towaryzamowienies = towaryzamowienies;
    }




}


